[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "benchcraftPy"
version = "0.1.0"
authors = [
  { name="Alp Eren Aydın" }
]
description = "A lightweight, precision decorator library for measuring execution time and peak memory usage in Python."
readme = "README.md"
requires-python = ">=3.8"
license = { text = "MIT" }
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/AlpErenAydin20/benchcraft"
"Bug Tracker" = "https://github.com/AlpErenAydin20/benchcraft/issues"